#!/usr/bin/python

##################
# dsviewer_npy.py
#
# Copyright David Baddeley, 2009
# d.baddeley@auckland.ac.nz
#
# This file may NOT be distributed without express permision from David Baddeley
#
##################

#!/usr/bin/python
# generated by wxGlade 0.3.3 on Mon Jun 14 06:48:07 2004

import wx
import os
import sys

#import viewpanel
#import PYME.cSMI as example
#import dCrop
#import logparser

import tables
import wx.py.crust

from arrayViewPanel import ArraySettingsAndViewPanel

class DSViewFrame(wx.Frame):
    def __init__(self, parent=None, title='', dstack = None, log = None, filename = None, mdh = None, size = (400,300)):
        wx.Frame.__init__(self,parent, -1, title, size=size)

        self.ds = dstack
        self.log = log
        self.mdh = mdh

        self.saved = False

#        if (dstack == None):
#            if (filename == None):
#                fdialog = wx.FileDialog(None, 'Please select Data Stack to open ...',
#                    wildcard='*.h5', style=wx.OPEN|wx.HIDE_READONLY)
#                succ = fdialog.ShowModal()
#                if (succ == wx.ID_OK):
#                    #self.ds = example.CDataStack(fdialog.GetPath().encode())
#                    #self.ds =
#                    self.h5file = tables.openFile(fdialog.GetPath())
#                    self.ds = self.h5file.root.ImageData
#                    self.SetTitle(fdialog.GetFilename())
#                    self.saved = True
#                    #fn =
#            else:
#                self.h5file = tables.openFile(filename)
#                self.ds = self.h5file.root.ImageData
#                self.SetTitle(filename)
#                self.saved = True
#                #self.ds = example.CDataStack(filename)
#                #self.SetTitle(fdialog.GetFilename())
#                self.saved = True

        self.vp = ArraySettingsAndViewPanel(self, self.ds)
        #grab a copy of the display options
        self.do = self.vp.do

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.vp, 1,wx.EXPAND,0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer)
        sizer.Fit(self)
        #sizer.SetSizeHints(self)

        # Menu Bar
        self.menubar = wx.MenuBar()
        self.SetMenuBar(self.menubar)
        tmp_menu = wx.Menu()
        F_EXPORT = wx.NewId()
        #F_CLOSE = wx.NewId()
        tmp_menu.Append(wx.ID_SAVEAS, "&Save As", "", wx.ITEM_NORMAL)
        tmp_menu.Append(F_EXPORT, "&Export Cropped", "", wx.ITEM_NORMAL)
        tmp_menu.Append(wx.ID_CLOSE, "Close", "", wx.ITEM_NORMAL)
        self.menubar.Append(tmp_menu, "File")

        mEdit = wx.Menu()
        EDIT_CLEAR_SEL = wx.NewId()
        EDIT_CROP = wx.NewId()
        mEdit.Append(EDIT_CLEAR_SEL, "Reset Selection", "", wx.ITEM_NORMAL)
        #mEdit.Append(EDIT_CROP, "Crop", "", wx.ITEM_NORMAL)
        self.menubar.Append(mEdit, "Edit")

        # Menu Bar end
        wx.EVT_MENU(self, wx.ID_SAVEAS, self.OnSave)
        wx.EVT_MENU(self, F_EXPORT, self.OnExport)
        wx.EVT_MENU(self, wx.ID_CLOSE, self.menuClose)
        wx.EVT_MENU(self, EDIT_CLEAR_SEL, self.clearSel)
        #wx.EVT_MENU(self, EDIT_CROP, self.crop)
        wx.EVT_CLOSE(self, self.OnCloseWindow)
		
        self.statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)

        self.Layout()
        self.update()

    def update(self):
        #self.vp.update()
        self.statusbar.SetStatusText('Slice No: (%d/%d)  x: %d  y: %d' % (self.do.zp, self.do.ds.shape[2], self.do.xp, self.do.yp))

    def OnSave(self, event=None):
        import dataExporter

        if 'getEvents' in dir(self.ds):
            evts = self.ds.getEvents()
        else:
            evts = []

        dataExporter.ExportData(self.vp.do.ds, self.mdh, evts)

        self.saved = True

    def OnExport(self, event=None):
        import dataExporter

        if 'getEvents' in dir(self.ds):
            evts = self.ds.getEvents()
        else:
            evts = []

        dataExporter.CropExportData(self.vp.view, self.mdh, evts)

    def menuClose(self, event):
        self.Close()

    def OnCloseWindow(self, event):
        if (not self.saved):
            dialog = wx.MessageDialog(self, "Save data stack?", "pySMI", wx.YES_NO|wx.CANCEL)
            ans = dialog.ShowModal()
            if(ans == wx.ID_YES):
                self.OnSave()
                self.Destroy()
            elif (ans == wx.ID_NO):
                self.Destroy()
            else: #wxID_CANCEL:   
                if (not event.CanVeto()): 
                    self.Destroy()
                else:
                    event.Veto()
        else:
            self.Destroy()
			
    def clearSel(self, event):
        self.vp.ResetSelection()
        self.vp.Refresh()
        
#    def crop(self, event):
#        cd = dCrop.dCrop(self, self.vp)
#        if cd.ShowModal():
#            ds2 = example.CDataStack(self.ds, cd.x1, cd.y1, cd.z1, cd.x2, cd.y2, cd.z2, cd.chs)
#            dvf = DSViewFrame(self.GetParent(), '--cropped--', ds2)
#            dvf.Show()



def View3D(data, title='' ):
    dvf = DSViewFrame(dstack = data, title=title, size=(500, 500))
    dvf.SetSize((500,500))
    dvf.Show()
    return dvf


class MyApp(wx.App):
    def OnInit(self):
        #wx.InitAllImageHandlers()
        if (len(sys.argv) > 1):
            vframe = DSViewFrame(None, sys.argv[1], filename=sys.argv[1])
        else:
            vframe = DSViewFrame(None, '')           

        self.SetTopWindow(vframe)
        vframe.Show(1)

        crFrame = wx.py.shell.ShellFrame(parent = vframe, locals = vframe.__dict__)
        crFrame.Show()
        print __file__
        crFrame.shell.runfile(os.path.join(os.path.dirname(__file__),'fth5.py'))
        return 1

# end of class MyApp

def main():
    app = MyApp(0)
    app.MainLoop()


if __name__ == "__main__":
    main()
