#!/usr/bin/env python
# generated by wxGlade 0.3.3 on Mon Jun 14 06:48:07 2004

import wx
#import sys
#sys.path.append(".")

#import viewpanel
#import example

from chanpanel import ChannelPan

class ChanFrame(wx.Dialog):
    def __init__(self, parent, chaninfo, title='Edit Shutters/Channels'):
        wx.Dialog.__init__(self,parent, -1, title)

        self.cp = ChannelPan(chaninfo, parent=self)
        self.bOK = wx.Button(self, -1, "OK")
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.cp, 1,wx.EXPAND,0)
        sizer.Add(self.bOK, 0,wx.TOP, 5)
        self.SetAutoLayout(1)
        self.SetSizer(sizer)
        sizer.Fit(self)
        #sizer.SetSizeHints(self)

        self.Layout()

        wx.EVT_BUTTON(self, self.bOK.GetId(), self.OnOK)
			
    def OnOK(self, event):
        self.EndModal(1)         

        
    

# end of class ViewFrame
