"""Zarr compatibility helpers for PYME tile pyramids.

This module provides a read-only fsspec filesystem (``pyme://``) which maps
standard zarr chunk keys to PYME tile filenames when PYME metadata is present,
and otherwise falls through to regular local filesystem behavior.
"""

from __future__ import absolute_import

import json
import os
import importlib

from . import PZFFormat

try:
    import numcodecs
    from numcodecs.abc import Codec
except ImportError:  # pragma: no cover - optional dependency
    numcodecs = None
    Codec = object

try:
    fsspec = importlib.import_module('fsspec')
    AbstractFileSystem = importlib.import_module('fsspec.spec').AbstractFileSystem
    LocalFileSystem = importlib.import_module('fsspec.implementations.local').LocalFileSystem
except Exception:  # pragma: no cover - optional dependency
    fsspec = None
    AbstractFileSystem = object
    LocalFileSystem = None


class PZFCodec(Codec):
    """Read-only numcodecs codec for PZF-encoded buffers."""

    codec_id = 'pyme-pzf'

    def encode(self, buf):
        raise NotImplementedError('PZFCodec is read-only and does not support encode()')

    def decode(self, buf, out=None):
        # numcodecs may pass ndarray-like objects; PZFFormat.loads expects bytes.
        if isinstance(buf, (bytes, bytearray)):
            payload = bytes(buf)
        else:
            payload = memoryview(buf).tobytes()

        data, _header = PZFFormat.loads(payload)

        if out is None:
            return data

        out[...] = data
        return out

    def get_config(self):
        return {'id': self.codec_id}

    @classmethod
    def from_config(cls, config):
        return cls()


class PYMEZarrFileSystem(AbstractFileSystem):
    """Read-only local filesystem shim for ``pyme://`` URLs.

    For a PYME pyramid with metadata in ``.zattrs`` under the ``pyme`` key, it
    translates chunk keys of the form ``level/z/x/y`` into the configured
    PYME tile filename schema. If PYME metadata is absent, all accesses are
    delegated directly to the local filesystem so ordinary zarr stores still
    work via ``pyme://``.
    """

    protocol = 'pyme'

    def __init__(self, *args, **kwargs):
        super(PYMEZarrFileSystem, self).__init__(*args, **kwargs)
        self._local = LocalFileSystem(auto_mkdir=False)
        self._spec_cache = {}

    @classmethod
    def _strip_protocol(cls, path):
        if isinstance(path, (tuple, list)):
            return [cls._strip_protocol(p) for p in path]

        if path.startswith('pyme://'):
            path = path[7:]
            if path.startswith('/'):
                return path
            return '/' + path
        return path

    def _find_store_root(self, local_path):
        p = os.path.abspath(local_path)
        if os.path.isfile(p):
            p = os.path.dirname(p)

        while True:
            if os.path.exists(os.path.join(p, '.zattrs')):
                return p

            parent = os.path.dirname(p)
            if parent == p:
                return None
            p = parent

    def _load_pyme_spec(self, root):
        cached = self._spec_cache.get(root, None)
        if cached is not None:
            return cached

        zattrs_path = os.path.join(root, '.zattrs')
        try:
            with open(zattrs_path, 'r') as fh:
                attrs = json.load(fh)
        except Exception:
            self._spec_cache[root] = None
            return None

        spec = attrs.get('pyme', None)
        self._spec_cache[root] = spec
        return spec

    def _map_path(self, path):
        local_path = os.path.abspath(self._strip_protocol(path))

        # Standard zarr keys or real paths should pass straight through.
        if os.path.exists(local_path):
            return local_path

        root = self._find_store_root(local_path)
        if root is None:
            return local_path

        spec = self._load_pyme_spec(root)
        if spec is None:
            return local_path

        rel = os.path.relpath(local_path, root).replace(os.sep, '/')
        parts = rel.split('/')

        # We only translate chunk keys: level/z/x/y
        # TODO - support other key schemas by parsing the key_schema in the spec and matching it to the path.
        # We ultimately want this to work wth the folder of PZF files that is generated by XYZTC acquisitions
        # as well.
        
        if len(parts) != 4:
            return local_path

        level_s, z_s, x_s, y_s = parts
        try:
            level = int(level_s)
            z = int(z_s)
            x = int(x_s)
            y = int(y_s)
        except ValueError:
            return local_path

        key_schema = spec.get('key_schema', '{level:d}/{z:03d}/{x:03d}/{y:03d}_{suff}{ext}')
        suffix = spec.get('suffix', 'img')
        ext = spec.get('extension', '.pzf')

        try:
            mapped_rel = key_schema.format(level=level, z=z, x=x, y=y, suff=suffix, ext=ext)
        except Exception:
            return local_path

        mapped_abs = os.path.join(root, *mapped_rel.split('/'))
        return mapped_abs

    def open(self, path, mode='rb', **kwargs):
        if mode not in ('rb', 'r'):
            raise NotImplementedError('PYMEZarrFileSystem is read-only')
        return self._local.open(self._map_path(path), mode=mode, **kwargs)

    def cat_file(self, path, start=None, end=None, **kwargs):
        return self._local.cat_file(self._map_path(path), start=start, end=end, **kwargs)

    def exists(self, path, **kwargs):
        mapped = self._map_path(path)
        return self._local.exists(mapped, **kwargs)

    def info(self, path, **kwargs):
        return self._local.info(self._map_path(path), **kwargs)

    def isdir(self, path):
        return self._local.isdir(self._map_path(path))

    def ls(self, path, detail=True, **kwargs):
        return self._local.ls(self._map_path(path), detail=detail, **kwargs)


if fsspec is not None:
    fsspec.register_implementation('pyme', PYMEZarrFileSystem, clobber=True)

if numcodecs is not None:
    numcodecs.register_codec(PZFCodec)
