package:
  name: enum-compat
  version: {{ GIT_DESCRIBE_TAG }}

#build:
#  noarch_python: True

source:
  git_url: https://github.com/jstasiak/enum-compat

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
  build:
    - python
  run:
    - python

about:
  home: github.com/jstasiak/enum-compat
  summary: This is a virtual package, its whole purpose is to install enum34 on Python older than 3.4. On Python 3.4+ it’s a no-op.
