#!/usr/bin/env python
# generated by wxGlade 0.3.3 on Thu Jun 17 09:17:37 2004

import wx

class CamPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CamPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, -1, "++")
        self.button_2 = wx.Button(self, -1, "+")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.button_3 = wx.Button(self, -1, "-")
        self.button_4 = wx.Button(self, -1, "--")
        self.combo_box_1 = wx.ComboBox(self, -1, choices=["1", "2"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.panel_1 = wx.Panel(self, -1, style=wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.bReset = wx.Button(self, -1, "Reset")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CamPanel.__set_properties
        self.button_1.SetSize((50, -1))
        self.button_2.SetSize((50, -1))
        self.text_ctrl_1.SetSize((50, -1))
        self.button_3.SetSize((50, -1))
        self.button_4.SetSize((50, -1))
        self.combo_box_1.SetSize((50, -1))
        self.combo_box_1.SetSelection(0)
        self.panel_1.SetSize((120, 120))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CamPanel.__do_layout
        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, -1, "Camera"), wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self, -1, "ROI"), wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self, -1, "Binning"), wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self, -1, "Int Time"), wx.VERTICAL)
        sizer_3.Add(self.button_1, 0, wx.TOP, 3)
        sizer_3.Add(self.button_2, 0, 0, 0)
        sizer_3.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_3.Add(self.button_3, 0, 0, 0)
        sizer_3.Add(self.button_4, 0, 0, 0)
        sizer_6.Add(sizer_3, 0, wx.EXPAND, 3)
        sizer_5.Add(self.combo_box_1, 0, wx.TOP, 3)
        sizer_6.Add(sizer_5, 0, 0, 0)
        sizer_2.Add(sizer_6, 0, wx.RIGHT, 4)
        sizer_4.Add(self.panel_1, 0, wx.ALL, 3)
        sizer_4.Add(self.bReset, 0, wx.TOP|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, 0, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

# end of class CamPanel


