#!/usr/bin/env python
# generated by wxGlade 0.3.3 on Fri Sep 24 09:21:34 2004

import wx

class ChanEditDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ChanEditDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_1_copy = wx.StaticText(self.panel_1, -1, "Name: ")
        self.tName_copy = wx.TextCtrl(self.panel_1, -1, "")
        self.cbSh0_copy = wx.CheckBox(self.panel_1, -1, "0")
        self.cbSh1_copy = wx.CheckBox(self.panel_1, -1, "1")
        self.cbSh2_copy = wx.CheckBox(self.panel_1, -1, "2")
        self.cbSh3_copy = wx.CheckBox(self.panel_1, -1, "3")
        self.cbSh4_copy = wx.CheckBox(self.panel_1, -1, "4")
        self.cbSh5_copy = wx.CheckBox(self.panel_1, -1, "5")
        self.cbSh6_copy = wx.CheckBox(self.panel_1, -1, "6")
        self.cbSh7_copy = wx.CheckBox(self.panel_1, -1, "7")
        self.cbBW_copy = wx.CheckBox(self.panel_1, -1, "B/W")
        self.cbRed_copy = wx.CheckBox(self.panel_1, -1, "Red")
        self.cbGreen1_copy = wx.CheckBox(self.panel_1, -1, "Green1")
        self.cbGreen2_copy = wx.CheckBox(self.panel_1, -1, "Green2")
        self.cbBlue_copy = wx.CheckBox(self.panel_1, -1, "Blue")
        self.bOK_copy = wx.Button(self.panel_1, -1, "OK")
        self.bCancel_copy = wx.Button(self.panel_1, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ChanEditDialog.__set_properties
        self.SetTitle("Edit Channel")
        self.bOK_copy.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ChanEditDialog.__do_layout
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1_copy = wx.BoxSizer(wx.VERTICAL)
        coloursize_copy = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, -1, "Colours"), wx.HORIZONTAL)
        shutsize_copy = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, -1, "Shutters"), wx.HORIZONTAL)
        namesize_copy = wx.BoxSizer(wx.HORIZONTAL)
        namesize_copy.Add(self.label_1_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        namesize_copy.Add(self.tName_copy, 1, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1_copy.Add(namesize_copy, 0, wx.EXPAND, 0)
        shutsize_copy.Add(self.cbSh0_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh1_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh2_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh3_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh4_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh5_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh6_copy, 0, wx.ALL, 3)
        shutsize_copy.Add(self.cbSh7_copy, 0, wx.ALL, 3)
        grid_sizer_1_copy.Add(shutsize_copy, 1, wx.ALL|wx.EXPAND, 3)
        coloursize_copy.Add(self.cbBW_copy, 0, wx.ALL, 3)
        coloursize_copy.Add(self.cbRed_copy, 0, wx.ALL, 3)
        coloursize_copy.Add(self.cbGreen1_copy, 0, wx.ALL, 3)
        coloursize_copy.Add(self.cbGreen2_copy, 0, wx.ALL, 3)
        coloursize_copy.Add(self.cbBlue_copy, 0, wx.ALL, 3)
        grid_sizer_1_copy.Add(coloursize_copy, 1, wx.ALL|wx.EXPAND, 3)
        sizer_4_copy.Add(grid_sizer_1_copy, 1, wx.EXPAND, 0)
        sizer_5_copy.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.bOK_copy, 0, wx.ALL, 3)
        sizer_5_copy.Add(self.bCancel_copy, 0, wx.ALL, 3)
        sizer_4_copy.Add(sizer_5_copy, 0, wx.EXPAND, 0)
        self.panel_1.SetAutoLayout(1)
        self.panel_1.SetSizer(sizer_4_copy)
        sizer_4_copy.Fit(self.panel_1)
        sizer_4_copy.SetSizeHints(self.panel_1)
        sizer_6.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_6)
        sizer_6.Fit(self)
        sizer_6.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class ChanEditDialog


